mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/audi
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/volkswagen
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/bmw
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/opel
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/hyundai
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/ford
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/nissan
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/porsche
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/mercedes_benz
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/mitsubishi
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/citroen
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/toyota
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/mazda
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/sonstige_autos
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/smart
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/renault
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/honda
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/alfa_romeo
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/fiat
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/peugeot
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/lancia
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/subaru
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/saab
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/chevrolet
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/mini
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/jaguar
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/seat
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/volvo
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/chrysler
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/daewoo
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/kia
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/rover
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/skoda
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/trabant
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/DataForAnalysis/suzuki
mkdir -p /Users/bismi/OneDrive/Desktop/DAUP-Project/CleanData/CleanedDataSet
